---
services:
  # Weaviate Vector Database
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.4
    container_name: ppm_weaviate_v2
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_API_BASED_MODULES: "true"
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      CLUSTER_HOSTNAME: "node1"
    networks:
      - ppm-network

  # FastAPI Backend v2 with Instructor
  backend:
    image: dixisouls/ppm-backend-v2:latest
    container_name: ppm_backend_v2
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - OLLAMA_URL=http://host.docker.internal:11434
      - PYTHONPATH=/app
    depends_on:
      - weaviate
    restart: unless-stopped
    volumes:
      - collected_info:/app/collected_info
    networks:
      - ppm-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  weaviate_data:
    driver: local
  collected_info:
    driver: local

networks:
  ppm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16